/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ConexaoBanco;
import f1.BDCircuito;
import f1.Circuito;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author u18321
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        
      
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_TotalCorredores = new javax.swing.JTextField();
        cmb_Data = new datechooser.beans.DateChooserCombo();
        txt_Descricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTcircuito = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPresquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        btn_listar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1074, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jLabel5.setText("Id_Autodromo");

        jLabel6.setText("Nome");

        jLabel7.setText("Endereco");

        jLabel8.setText("Cidade");

        jLabel9.setText("Pais");

        jLabel10.setText("Descrição");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(884, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(121, 121, 121))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Autódromo", jPanel2);

        jLabel1.setText("Nome");

        jLabel2.setText("Total Corredores");

        jLabel3.setText("Data");

        jLabel4.setText("Descrição");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });
        txt_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomeKeyTyped(evt);
            }
        });

        txt_TotalCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TotalCorredoresActionPerformed(evt);
            }
        });
        txt_TotalCorredores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TotalCorredoresKeyTyped(evt);
            }
        });

        cmb_Data.setNothingAllowed(false);
        cmb_Data.setFormat(2);

        txt_Descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DescricaoKeyTyped(evt);
            }
        });

        JTcircuito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Circuito", "nome_Circuito", "Total Corredores", "Data", "Descrição", "Imagem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTcircuito);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPresquisar.setText("Pesquisar");
        btnPresquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresquisarActionPerformed(evt);
            }
        });

        jLabel11.setText("Id para Ações");

        btn_listar.setText("Listar");
        btn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_TotalCorredores, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                        .addComponent(txt_Descricao)))
                                .addGap(90, 90, 90))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btn_listar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPresquisar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                    .addComponent(cmb_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_TotalCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cmb_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txt_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPresquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_listar)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Circuito", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //criando metodo para ler valores do banco de dados e colocar na Jtable
    public void readJTable(){
          DefaultTableModel modelo =(DefaultTableModel) JTcircuito.getModel();
          modelo.setNumRows(0);
          Connection c = ConexaoBanco.criaConexao();
          
          for(Circuito cc : BDCircuito.ListarCircuito(c)){
              
              modelo.addRow(new Object[]{cc.getId(),
                                         cc.getNome_circuito(),
                                         cc.getTotal_corredoes(),
                                         cc.getData(),
                                         cc.getDescricao(),
                                         cc.getImg()});
          }
          
    }
    
    private void txt_TotalCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TotalCorredoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TotalCorredoresActionPerformed

    private void txt_nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeKeyTyped

        int totalCharacter = 25;
        
        if(txt_nome.getText().length() >= totalCharacter){
            JOptionPane.showMessageDialog(null,"Excedeu o limite de characteres");
            evt.consume();
        }
        
    }//GEN-LAST:event_txt_nomeKeyTyped

    private void txt_DescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DescricaoKeyTyped
         int totalCharacter = 200;
        
        if(txt_Descricao.getText().length() >= totalCharacter){
            JOptionPane.showMessageDialog(null,"Excedeu o limite de characteres");
            evt.consume();
            
        }
        
        
    }//GEN-LAST:event_txt_DescricaoKeyTyped

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        //adicionando um novo circuito ao banco de dados
        
        System.out.println(cmb_Data.getText());
        if(txt_nome.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite um nome");
        }
        if(txt_TotalCorredores.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite Total de Corredores");
        }
        else if(txt_Descricao.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Digite uma Descrição");
        }
        else{
           try{
                   Connection conection = ConexaoBanco.criaConexao();
                   Circuito circuito;
                
                   //criando um novo circuito para ser adicionado no bd
                   circuito = new Circuito(txt_nome.getText(),
                        Integer.parseInt(txt_TotalCorredores.getText()),
                        cmb_Data.getText(),
                        txt_Descricao.getText()
                );
                
                   BDCircuito.InserirCircuito(circuito, conection);
                   readJTable();
                  
                   //deixando os campos das tabela limpo
                   txt_id.setText("");
                   txt_nome.setText("");
                   txt_TotalCorredores.setText("");
                   txt_Descricao.setText("");
                   cmb_Data.setText("");
           }catch(Exception ex){
               ex.getMessage();
           }    
            
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void txt_TotalCorredoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TotalCorredoresKeyTyped
        // TODO add your handling code here:
        //Deixando digitar apenas numeros;
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digitar apenas numeros");
        }
    }//GEN-LAST:event_txt_TotalCorredoresKeyTyped

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        //botao caso o usuario queira modificar algum dados
        if(txt_nome.getText().equals("") && txt_id.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Digite o nome ou o id que deseja Alterar:");
           
        }if(!txt_id.getText().equals("")){
            if(txt_Descricao.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Digite uma descrição");
            }if(txt_TotalCorredores.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Digite total de corredores");  
            }
            if(txt_nome.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Digite um nome");  
            }
            if(cmb_Data.getText().equals("")){
                  JOptionPane.showMessageDialog(null, "Digite uma data");  
            }
            else{
                Connection c;
                try{
                    c = ConexaoBanco.criaConexao();

                    BDCircuito.alterarId(txt_id.getText(), txt_nome.getText(), txt_TotalCorredores.getText(), cmb_Data.getText(), txt_Descricao.getText(), c);


                    c.close();//fechando conexão
                    readJTable();
                    txt_id.setText("");
                    txt_nome.setText("");
                    txt_TotalCorredores.setText("");
                    txt_Descricao.setText("");
                }catch(Exception ex){
                        System.out.println(ex.getMessage());
                } 
            }  
            
        }
        else if(!txt_nome.getText().equals("")){
            if(txt_Descricao.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Digite uma descrição");
            }if(txt_TotalCorredores.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Digite total de corredores");  
            }
            if(cmb_Data.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Digite um nome");  
            }
            else{
                Connection c;
                try{
                    c = ConexaoBanco.criaConexao();

                   BDCircuito.alterar(txt_nome.getText(),txt_TotalCorredores.getText(),txt_Descricao.getText(), cmb_Data.getText(), c);


                    c.close();//fechando conexão
                    readJTable();
                    txt_id.setText("");
                    txt_nome.setText("");
                    txt_TotalCorredores.setText("");
                    txt_Descricao.setText("");
                }catch(Exception ex){
                        System.out.println(ex.getMessage());
                } 
            }  
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        if(txt_nome.getText().equals("") && txt_id.getText().equals("")){//deletar pelo nome do circuito
            JOptionPane.showMessageDialog(null, "Digite o nome ou o id que deseja excluir:");
        }if(!txt_nome.getText().equals("")) {
              Connection connection = null;
            try {
              
                connection = ConexaoBanco.criaConexao();
            
                BDCircuito.deletar(txt_nome.getText(), connection);
                readJTable();
                   txt_id.setText("");
                   txt_nome.setText("");
                   txt_TotalCorredores.setText("");
                   txt_Descricao.setText("");
                   cmb_Data.setText("");
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Erro ao deletar");
            }finally{
                  try {
                      connection.close();
                  } catch (SQLException ex) {
                      Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                  }
            }
          
        }else if(!txt_id.getText().equals("")){//caso queira deletar pelo id do circuito
             try {
                Connection connection;
                connection = ConexaoBanco.criaConexao();
            
                BDCircuito.deletarId(txt_id.getText(), connection);
                readJTable();
                
                   txt_id.setText("");
                   txt_nome.setText("");
                   txt_TotalCorredores.setText("");
                   txt_Descricao.setText("");
                   cmb_Data.setText("");
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Erro ao deletar");
            }
            
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPresquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresquisarActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
         Connection connection = null;
        if(txt_nome.getText().equals("")&&txt_id.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Digite um nome ou um id para consultar");
        }
        if(!txt_nome.getText().equals("")){
            
            ResultSet rs = null;
            try {
               
                connection = ConexaoBanco.criaConexao();
               rs =  BDCircuito.consultarNome(txt_nome.getText(), connection);
               DefaultTableModel modelo =(DefaultTableModel) JTcircuito.getModel();
               modelo.setNumRows(0);
               
               while(rs.next()){
                 
                   //passando os dados para dentro da tabela 
                   
                    
                    modelo.addRow(new Object[]{
                        rs.getString("id_circuito"),
                         rs.getString("nome_circuito"),
                        rs.getString("total_corredores"),
                         rs.getString("data"),
                         rs.getString("descricao"),
                         rs.getBytes("imagem")
                    });
               }
                   txt_id.setText("");
                   txt_nome.setText("");
                   txt_TotalCorredores.setText("");
                   txt_Descricao.setText("");
                   cmb_Data.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    connection.close();
                    rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                }
               

            }
        }else if(!txt_id.getText().equals("")){
             ResultSet rs = null;
            try {
               
                connection = ConexaoBanco.criaConexao();
                rs =  BDCircuito.consultar(txt_id.getText(), connection);
                //colocando dados dentro da tabela visual
                DefaultTableModel modelo =(DefaultTableModel) JTcircuito.getModel();
               modelo.setNumRows(0);
               while(rs.next()){
                  modelo.addRow(new Object[]{
                        rs.getString("id_circuito"),
                         rs.getString("nome_circuito"),
                        rs.getString("total_corredores"),
                         rs.getString("data"),
                         rs.getString("descricao"),
                         rs.getBytes("imagem")
                    });
               }
                   txt_id.setText("");
                   txt_nome.setText("");
                   txt_TotalCorredores.setText("");
                   txt_Descricao.setText("");
                   cmb_Data.setText("");
                   
                   
            } catch (SQLException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    connection.close();
                    rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                }
               
             }
        
        }
       
    }//GEN-LAST:event_btnPresquisarActionPerformed

    private void btn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarActionPerformed
        // TODO add your handling code here:
        readJTable();
    }//GEN-LAST:event_btn_listarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTcircuito;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPresquisar;
    private javax.swing.JButton btn_listar;
    private datechooser.beans.DateChooserCombo cmb_Data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_Descricao;
    private javax.swing.JTextField txt_TotalCorredores;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
